server:
  port: 8082

spring:
  application:
    name: comprovante-gravador
  datasource:
    url: jdbc:h2:mem:gravador;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info
